name: Python Flask Continuous Integration - Linting and Docker Iamge Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: debian-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Install linting tool
        run: pip install flake8

      - name: Linting
        run: flake8 app/

  image:
    needs: linting

    runs-on: debian-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build .
