name: Python Flask Continuous Integration - Linting, Testing and Docker Image Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]


permissions:
  contents: read
  packages: write

jobs:
  linting:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Install linting tool
        run: pip install flake8

      - name: Linting
        run: flake8 app/

  testing:
    needs: linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install app requirements
      run: pip install -r requirements.txt

    - name: Install testing tool
      run: pip install pytest

    - name: Install Mock
      run: pip install pytest-mock

    - name: Run test
      run: python -m pytest

  image:
    needs: testing
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64, linux/amd64, linux/arm64/v8
          context: .
          push: true
          tags: ghcr.io/cecilia-malves/peter-cecilia-sw-dev:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max
